### PR TITLE
Feature/hruid longint

### PR DESCRIPTION
**Pull request by arbennett**
This pull request allows for HRU ID to have data type int64

This supercedes #328

### CODE REVIEW

**Comment by andywood** [comment]
HI Andrew,
Glad to see these changes merged.  Were these modifications taken from the
code changes I made last year to be able to run the HUC12-based summa
models?  I never did a PR for those because there was some unfinished
business related to handling IDs as strings.

https://github.com/andywood/summa/tree/string_IDs

Cheers,
-Andy

**Comment by arbennett** [comment]
Yep, these were the changes just to allow for int64 hruid. This still doesn't support string IDs.

**Comment by andywood** [comment]
Just curious -- were these changes copied from my branch, ie the version
some of us are using for the HUC12-based simulations?

the reason I ask is to know if your changes were implemented differently,
or if the branch code I'm using is still consistent with it.  it sounds
like it doesn't pull over all the changes that were oriented toward
strings, but that's still an interest down the road.

Sorry, I don't have time to compare the codes right now, but just wondered.

-Andy

**Comment by bartnijssen** [comment]
Hi @andywood : These changes were from your own PR from last year. See here for details: https://github.com/NCAR/summa/pull/339

**Comment by arbennett** [comment]
As @bartnijssen said, yes these were from your PR. I just separated them out to remove the changes to the Makefile.

**Pull request merged**
