### PR TITLE
Feature/single layer solution

### PR DESCRIPTION
**Pull request by martynpclark**
Implementation of operator splitting to the level of individual layers. Provides a solution for soil hydrology. The full solution (including thermodynamics) is under development.

### CODE REVIEW

**Comment by martynpclark** [comment]
Added initial capabilities for the single layer solution over snow+soil layers.

This branch is ready for testing over the Columbia.

**Comment by martynpclark** [comment]
This branch is now complete. It is ready for detailed testing.

**Comment by bartnijssen** [comment]
@martynpclark : Does the last iteration include the thermodynamics or is this still for hydrology only?

**Comment by martynpclark** [comment]
The current version is complete (thermodynamics and hydrology)

**Comment by bartnijssen** [comment]
@arbennett : Can you do a review for this PR?

**Pull request merged**
