### PR TITLE
Feature/nldas adjustments

### PR DESCRIPTION
**Pull request by martynpclark**
Minor adjustments to run over the NLDAS domain

### CODE REVIEW

**Comment by bartnijssen** [comment]
@martynpclark : Does this build OK on your end? For some reason the travis build failed on the `summa_install` part, but it is not clear to me why .... When you build locally, which compiler are you using?

**Comment by martynpclark** [comment]
@bartnijssen -- I'm using `ifort` on `cheyenne`

**Comment by martynpclark** [comment]
@bartnijssen -- do you know which compiler causes the failure? If so I can test locally.

**Comment by bartnijssen** [comment]
I'm not even sure it's the compiler since there is no error message at all. It may just be that the compilation stalled. Let me kick it off one more time. On travis we are currently using gcc-6, which we need to update to 7 anyway, so may be that is the route to go before wasting your time.

**Comment by bartnijssen** [comment]
@martynpclark : Compilation fails during compilation of `netcdf/read_icond.f90` with the message:

`Fatal Error: Can't open module file 'updatstate_module.mod'`

which is not built till later. Rerunning the compilation works (if you do not do a `make clean`), because the file does get created eventually.

The cleanest solution would be if we don’t need to call `updateSoil` from inside `read_icond` (in the same way that we do not call `updateSnow` from inside `read_icond`). In that case there is no dependency in the `netcdf` directory on things that are compiled later.

If that is not possible then we just need to reorg some of the directories a bit (or create the logic in the Makefile).

**Comment by martynpclark** [comment]
@bartnijssen -- thanks. I forgot to update the Makefile. Now updated.

**Pull request merged**
