### PR TITLE
Feature/scale matrices

### PR DESCRIPTION
**Pull request by martynpclark**
Scaled the matrices used in the numerical solution. This pull request should be processed AFTER feature/nrgSolvEnthalpy.

### CODE REVIEW

**Comment by martynpclark** [comment]
PLEASE DELAY PROCESSING THIS PR FOR NOW. I AM WORKING ON ANOTHER BRANCH, AND IT MAKES MORE SENSE TO INTEGRATE THIS OTHER BRANCH BEFORE THIS ONE.

**Comment by bartnijssen** [comment]
@martynpclark : I'll still hold off merging till I hear from you.

**Comment by martynpclark** [comment]
Thanks. I'm getting back into the saddle now.

On 3/16/16 10:33 PM, Bart Nijssen wrote:
>
> @martynpclark <https://github.com/martynpclark> : I'll still hold off 
> merging till I hear from you.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/NCAR/summa/pull/110#issuecomment-197696280>
>

-- 
Martyn Clark
Hydrometeorological Applications Program
Research Applications Laboratory, National Center for Atmospheric Research
3450 Mitchell Lane
Boulder, CO 80301
Tel: 303-497-2732
https://staff.ucar.edu/users/mclark

**Comment by bartnijssen** [comment]
@martynpclark : Should this PR remain open or do you want to close it and reopen it when it is ready?

**Comment by martynpclark** [comment]
@bartnijssen: Closed for now.

**Pull request closed without merging**
