### PR TITLE
Feature/nrg solv enthalpy

### PR DESCRIPTION
**Pull request by martynpclark**
Formulates the heat equation in terms of enthalpy (though the enthalpy capabilities are "switched off" in order to reproduce results from previous branches).

The code has been run through all summa test cases, providing simulations very similar to the previous branches (results are not identical because the the numerical formulation has changed).

NOTE: this branch should be merged AFTER feature/improveConv

### CODE REVIEW

**Comment by bartnijssen** [comment]
@martynpclark : Is this ready to review and merge?

**Comment by martynpclark** [comment]
No, not yet. I plan to submit a pull request for a code refactor 
tomorrow, and then I'll reactivate these other pull requests.

On 3/16/16 10:32 PM, Bart Nijssen wrote:
>
> @martynpclark <https://github.com/martynpclark> : Is this ready to 
> review and merge?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/NCAR/summa/pull/109#issuecomment-197695882>
>

-- 
Martyn Clark
Hydrometeorological Applications Program
Research Applications Laboratory, National Center for Atmospheric Research
3450 Mitchell Lane
Boulder, CO 80301
Tel: 303-497-2732
https://staff.ucar.edu/users/mclark

**Comment by bartnijssen** [comment]
@martynpclark : Should this PR remain open or do you want to close it and reopen it when it is ready?

**Comment by martynpclark** [comment]
@bartnijssen: Closed for now.

**Pull request closed without merging**
